### ISSUE TITLE
Create a /reset command

### ISSUE THREAD

**Issue by danileo** [danileo/autobot#6]
The /reset command should delete all the preferences stored in the database (for the given chat, see #5).

**Comment by MatteoDrago** [comment]
I propose an automatic reset for any chat at midnight UTC+01:00. Or at least an option to make the reset autonomous for a given chat! I'm starting looking at the code

**Comment by danileo** [comment]
The /reset command (which effects depend on the chat it is used in) has been provided in commit a2e688bf948234b0036d14ae7bdf286113db0f57. This is a good base for making an automatic reset.

**Comment by danileo** [comment]
The cron job can now call a specific URL for deleting all preferences (commit 7161c99aff8708803f5e0d5860b495a4bd5b28f7).
